# The version of Contiv binaries to use
contiv_version: v0.1-05-02-2016.23-10-27.UTC

# TCP port that Netmaster listens for network connections
netmaster_port: 9999

# TCP port that Netplugin listens for network connections
netplugin_port: 6640
contiv_rpc_port1: 9001
contiv_rpc_port2: 9002
contiv_rpc_port3: 9003

# IP address of the interface used for control communication within the cluster
# It needs to be reachable from all nodes in the cluster.
netplugin_ctrl_ip: "{{ contiv_control_ip }}"

# IP used to terminate vxlan tunnels
#netplugin_vtep_ip: "{{ hostvars[inventory_hostname]['ansible_' + netplugin_interface].ipv4.address }}"

# Interface used by Netplugin for inter-host traffic when encap_mode is vlan.
# The interface must support 802.1Q trunking.
netplugin_interface: "{{ contiv_network_if }}"

# Interface used to bind Netmaster service
nemaster_interface: "{{ contiv_control_ip }}"

# Path to the contiv binaries
bin_dir: /usr/bin

# Path to the contivk8s cni binary
cni_bin_dir: /opt/cni/bin

# Contiv config directory
contiv_config_dir: /opt/contiv/config

# Directory to store downloaded Contiv releases
contiv_releases_directory: /opt/contiv
contiv_current_release_directory: "{{ contiv_releases_directory }}/{{ contiv_version }}"

#The default url to download the Contiv tar's from
contiv_download_url_base: "https://github.com/contiv/netplugin/releases/download"
contiv_download_url: "{{ contiv_download_url_base }}/{{ contiv_version }}/netplugin-{{ contiv_version }}.tar.bz2"

# This is where kubelet looks for plugin files
kube_plugin_dir: /usr/libexec/kubernetes/kubelet-plugins/net/exec

# Specifies routed mode vs bridged mode for networking (bridge | routing)
# if you are using an external router for all routing, you should select bridge here
netplugin_fwd_mode: routing

# Contiv fabric mode aci|default
contiv_fabric_mode: default

# Encapsulation type vlan|vxlan to use for instantiating container networks
contiv_encap_mode: vxlan

# Backend used by Netplugin for instantiating container networks
netplugin_driver: ovs

# Create a default Contiv network for use by pods
contiv_default_network: false

# The following are aci specific parameters when contiv_fabric_mode: aci is set.
# Otherwise, you can ignore these.
apic_url: ""
apic_username: ""
apic_password: ""
apic_leaf_nodes: ""
apic_phys_dom: ""
apic_contracts_unrestricted_mode: no
apic_epg_bridge_domain: not_specified
is_atomic: False
kube_cert_dir: "/etc/origin/node"
master_name: "{{ groups['masters'][0] }}"
etcd_url: "{{ hostvars[groups['masters'][0]].contiv_control_ip }}:2379"
