---
# This playbook deploys a kubernetes cluster 
# with the default addons.

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

# install contiv netmaster
- hosts: masters
  sudo: yes
  roles:
    - { role: contiv, contiv_role: netmaster, when: networking == 'contiv' }

# install contiv netplugin
- hosts: nodes
  sudo: yes
  roles:
    - { role: contiv, contiv_role: netplugin, when: networking == 'contiv' }
